### PR TITLE
custom tab bar for animating sf symbols

### PR DESCRIPTION
**Pull request by mariamBabutsidze**
Hi @mzellhuber, I had to create custom tab bar to use new sf symbols to animate them. Tell me your opinion if you like it, else we can just use TabView. We can also change colors of the symbols and animation. Please see the recording in the review of the pull request.

### CODE REVIEW

**Comment by mzellhuber** [comment]
Hey @mariamBabutsidze, great work on the tab bar! It's really looking good. Just a small thing I noticed: it appears slightly off-center on my screen. I'm not sure if you're experiencing the same thing.
By the way, I couldn't find the video. Where should I be looking? 😄

**Comment by mariamBabutsidze** [comment]
https://github.com/mzellhuber/TravelApp/assets/60294556/153570f1-f253-456e-91f6-e68b7a5356b3

**Comment by mariamBabutsidze** [comment]
I thought I uploaded file, now you can see it I guess. Can you share me screenshot @mzellhuber ? I have one problem. I could not align items correctly. I will try to correct.

**Comment by mariamBabutsidze** [comment]
https://github.com/mzellhuber/TravelApp/assets/60294556/d8da2530-3190-444a-8104-de9c9f7b929f

Corrected version

**Comment by mzellhuber** [comment]
It's so pretty!!

**Review by mzellhuber — APPROVED** [review]

**Pull request merged**
